## MICE (Multivariate Imputation By Chained Equations)

In [37]:
import pandas as pd
import requests
from io import StringIO
import numpy as np

In [44]:
res = requests.get('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day40-iterative-imputer/50_Startups.csv').text
df = np.round(pd.read_csv(StringIO(res))[['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']]/10000)
np.random.seed(9)
df_missing = df.drop(columns=['Profit'])
df_missing = df_missing.sample(5)
df_missing.loc[21, 'R&D Spend'] = np.nan
df_missing.loc[37, 'Administration'] = np.nan
df_missing.loc[2, 'Marketing Spend'] = np.nan
df_missing

    R&D Spend  Administration  Marketing Spend
21        NaN            15.0             30.0
37        4.0             NaN             20.0
2        15.0            10.0              NaN
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [55]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.linear_model import LinearRegression
from sklearn.impute import IterativeImputer
imp = IterativeImputer(max_iter=10, estimator=LinearRegression(), random_state=42)

In [56]:
pd.DataFrame(imp.fit_transform(df_missing), columns=['R&D Spend', 'Administration', 'Marketing Spend'])

   R&D Spend  Administration  Marketing Spend
0  14.828693       15.000000        30.000000
1   4.000000       21.535154        20.000000
2  15.000000       10.000000        20.572599
3  12.000000       16.000000        26.000000
4   2.000000       15.000000         3.000000